language: c
script: bash -ex .travis-ci.sh
sudo: required
env:
  global:
  matrix:
  - PINS="lwt" #needed for Lwt_unix.bind, can be removed once lwt > 3.0.0 is released
  - OCAML_VERSION=4.03 PACKAGE=tcpip MIRAGE_MODE=unix
  - UPDATE_GCC_BINUTILS=1 OCAML_VERSION=4.03 PACKAGE=tcpip MIRAGE_MODE=xen
  - UPDATE_GCC_BINUTILS=1 OCAML_VERSION=4.04 PACKAGE=tcpip MIRAGE_MODE=ukvm
  - OCAML_VERSION=4.04 PACKAGE=tcpip MIRAGE_MODE=unix
  - UPDATE_GCC_BINUTILS=1 OCAML_VERSION=4.04 PACKAGE=tcpip MIRAGE_MODE=xen
  - UPDATE_GCC_BINUTILS=1 OCAML_VERSION=4.04 PACKAGE=tcpip MIRAGE_MODE=ukvm
